
import pypdf
import os
import sys

# Add the project root to sys.path to import ChromaService
sys.path.append(os.path.join(os.getcwd(), "ai-service"))

from services.chroma_service import ChromaService

def chunk_text(text, chunk_size=500, overlap=50):
    chunks = []
    for i in range(0, len(text), chunk_size - overlap):
        chunks.append(text[i:i + chunk_size])
    return chunks

def ingest_file(file_path):
    if not os.path.exists(file_path):
        print(f"File not found: {file_path}")
        return

    print(f"Ingesting: {file_path}")
    
    full_text = ""
    if file_path.endswith(".pdf"):
        with open(file_path, "rb") as f:
            reader = pypdf.PdfReader(f)
            for page in reader.pages:
                full_text += page.extract_text() + "\n"
    else:
        with open(file_path, "r", encoding="utf-8") as f:
            full_text = f.read()
    
    chunks = chunk_text(full_text)
    
    chroma = ChromaService()
    
    documents = chunks
    metadatas = [{"source": os.path.basename(file_path)} for _ in chunks]
    ids = [f"{os.path.basename(file_path)}_{i}" for i in range(len(chunks))]
    
    print(f"Adding {len(chunks)} chunks to ChromaDB...")
    chroma.add_documents(documents, metadatas, ids)
    print("Ingestion complete.")

def ingest_path(path):
    if os.path.isdir(path):
        for root, dirs, files in os.walk(path):
            for file in files:
                if file.endswith((".pdf", ".txt")):
                    ingest_file(os.path.join(root, file))
    else:
        ingest_file(path)

# Generated by GitHub Copilot
def delete_file_embeddings(file_basename):
    chroma = ChromaService()
    collection = chroma.collection

    # Find all IDs with the old file as source
    results = collection.get(where={"source": file_basename})
    ids_to_delete = results.get("ids", [])

    if ids_to_delete:
        collection.delete(ids=ids_to_delete)
        print(f"Deleted {len(ids_to_delete)} embeddings from {file_basename}")
    else:
        print("No embeddings found for old file.")

if __name__ == "__main__":

    
    delete_file_embeddings("Tool-13_Regulatory_Change_Management.pdf")

    # List of files or directories to ingest
    targets = [
        r"d:\pranathi\projects\campus pe\regulatory-change-management\regulatory_kb.txt",
        r"d:\pranathi\projects\campus pe\regulatory-change-management\internal_policies.txt"
    ]
    
    for target in targets:
        ingest_path(target)
