// Generated by GitHub Copilot
import React, { useState, useEffect, createContext, useContext } from "react";
import { BrowserRouter, Routes, Route, Navigate } from "react-router-dom";
import Login from "./pages/Login";
import Dashboard from "./pages/Dashboard";
import List from "./pages/List";
import Detail from "./pages/Detail";
import Form from "./pages/Form";
import EditRegulatoryChangeForm from "./pages/EditRegulatoryChangeForm";
import Layout from "./components/Layout";

// Auth context for global token state
const AuthContext = createContext();

export function useAuth() {
    return useContext(AuthContext);
}

export default function App() {
    const [token, setToken] = useState(() => localStorage.getItem("token"));

    // Listen for storage changes (multi-tab support)
    useEffect(() => {
        const handler = () => setToken(localStorage.getItem("token"));
        window.addEventListener("storage", handler);
        return () => window.removeEventListener("storage", handler);
    }, []);

    // Provide login/logout helpers
    const login = (tokenValue) => {
        localStorage.setItem("token", tokenValue);
        setToken(tokenValue);
    };
    const logout = () => {
        localStorage.removeItem("token");
        localStorage.removeItem("role");
        setToken(null);
    };

    return (
        <AuthContext.Provider value={{ token, login, logout }}>
            <BrowserRouter>
                <Routes>
                    <Route path="/login" element={<Login />} />
                    <Route path="/dashboard" element={token ? <Layout><Dashboard /></Layout> : <Navigate to="/login" />} />
                    <Route path="/changes" element={token ? <Layout><List /></Layout> : <Navigate to="/login" />} />
                    <Route path="/changes/new" element={token ? <Layout><Form /></Layout> : <Navigate to="/login" />} />
                    <Route path="/changes/:id" element={token ? <Layout><Detail /></Layout> : <Navigate to="/login" />} />
                    <Route path="/changes/:id/edit" element={token ? <Layout><EditRegulatoryChangeForm /></Layout> : <Navigate to="/login" />} />
                    <Route path="*" element={<Navigate to={token ? "/dashboard" : "/login"} />} />
                </Routes>
            </BrowserRouter>
        </AuthContext.Provider>
    );
}